mod browse;
mod config;
mod core_subscription;
mod decoding;
mod discovery;
mod metadata;
mod provider;
mod replay;
mod statement;
pub use provider::{NatsExecutor, NatsProvider};

fn capabilities() -> serde_json::Value {
    serde_json::json!({
        "operations": ["check", "fetch_page", "query_page", "execute_query", "follow_page", "stop_follow"],
        "server_discovery": {"resource": "nats.servers", "path": [], "subject": "$SYS.REQ.SERVER.PING.STATSZ", "window_ms": 1000, "maximum_observed_servers": 100, "response_bytes_total": 1048576, "behavior": "Opt-in system-account request; deduplicate by server ID and preserve full reply JSON. One observation page, refresh to rediscover. Missing or late responders are not proof of absence. No returned hosts are contacted. Excess counts/bytes and permission failures are errors; --check does not request discovery."},
        "replay": {"resource": "nats.query", "path": ["stream"], "format": "CONSUME stream [subject] [seq|time start..end]; no body", "subject": "optional second token, default >; native subject wildcard matching", "seq": "seq start..end; start is a positive inclusive sequence, end a positive exclusive one, either may be omitted", "time": "time start..end; start is an RFC3339 timestamp resolving to a sequence, not a per-message filter; end is a sequence. Bounded scan of at most 100 subject-matching messages per page; empty result pages can continue", "bookmarks": "bind query, executor and stream version; no consumer creation or ACKs"},
        "publish": {"resource": "nats.query", "path": ["stream"], "format": "PRODUCE stream subject, optional Name: value header lines, then the payload after a blank line", "headers": "Header lines between the verb line and the blank line; names and values are trimmed and duplicates keep their order", "encoding": "A reserved Onetui-Encoding line decodes the payload as base64, hex or utf-8 (default) and is consumed rather than sent; whitespace in base64 and hex payloads is ignored", "target": "Nats-Expected-Stream binds the named stream on the server", "result": "JetStream acknowledgment with stream and sequence; no automatic retry"},
        "example_toml": "[connections.events]\nkind = 'nats'\nservers = ['tls://nats.example.net:4222']\nusername_env = 'NATS_USERNAME'\npassword_env = 'NATS_PASSWORD'\n",
        "configuration_behavior": "Unknown fields, wrong types and invalid entries fail even on unselected aliases. No URL/path expansion. No credentials when authentication fields are omitted. Selected secrets must be nonblank Unicode, max 65536 bytes; only credentials_env permits line breaks and tabs. Reference names use ASCII letters, digits, underscores or hyphens. Authentication modes are mutually exclusive. ca_file replaces native roots.",
        "session": "Lazy async-nats client retained for the selected alias; native PING/PONG every 15 seconds. Consecutive reconnect attempts capped at configured server count, TCP connection timeout 1 second. Server-rejected requests keep the connected client. Requests and shutdown are deadline bounded.",
        "limits": {"page_rows": 100, "page_bytes": 1048576, "response_bytes": 1048576, "client_queue": 16, "subscription_queue": 16, "rss_guarantee": false},
        "paths": {"nats.resources": [], "nats.servers": [], "nats.subjects": [], "nats.core_messages": ["configured subject"], "nats.streams": [], "nats.messages": ["stream"], "nats.query": ["stream"], "nats.stream_info": ["stream"], "nats.consumer_streams": [], "nats.consumers": ["stream"], "nats.consumer_info": ["stream", "consumer"], "nats.kv_buckets": [], "nats.kv_keys": ["bucket"], "nats.kv_history": ["bucket", "key"], "nats.kv_value": ["bucket", "key"], "nats.object_buckets": [], "nats.objects": ["bucket"], "nats.object": ["bucket", "name"], "nats.object_info": ["bucket", "name"], "nats.object_chunks": ["bucket", "name"]},
        "inspection": "Consumer configuration, pending/ACK/redelivery state are read without consuming. KV keys expose retained revisions and native delete/purge headers; follow watches one key. Object metadata includes deleted entries and links. Contents are lazy original-byte chunks, pinned to metadata version; complete reads check size/chunk count but not digest. Object links are not followed automatically.",
        "core_subscriptions": "Choose Subjects, open a configured subject, then press f. One subscription per selected connection, no queue group or reply publishing. Stop unsubscribes and discards queued messages; restart has no replay. Queue overflow or disconnect stops following with a loss warning. Core headers are SDK values, not original wire bytes.",
        "paging": "Stream names use server offset pagination. Messages use stream sequences and a captured last-sequence boundary; sparse sequences are skipped by the server. Bookmarks bind executor, resource, stream creation time and window. Reads are not snapshots; retention or stream replacement can invalidate positions.",
        "values": "Message data and the original JetStream NATS header block are bytes; absent headers are null, empty payloads are empty bytes. Subject, sequence and stored timestamp are separate fields. Exact-subject Avro/Protobuf bindings add JSON/native inspection, schema identity and per-message errors without replacing raw data.",
        "decoding": {"framing": "raw (default) or explicit confluent schema-ID payload prefix; no auto-detection", "schema_bytes": 262144, "payload_bytes": 65536, "preview_bytes": 65536, "error_bytes": 512, "cache": "files/catalogs/Buf: selected connection lifetime including load failures; registry: eight exact IDs per binding including lookup failures; reconnect to reload", "execution": "bounded blocking parsing with at most two active tasks, deadline/cancellation checks; file reads reject non-regular files", "sources": "explicit files, directory catalogs, Confluent Avro/Protobuf registries and Buf Protobuf descriptors; optional Avro reader file; imports required"},
        "following": {"start": "after the selected stream's current last sequence", "poll_interval_ms": 1000, "buffer_rows": 100, "buffer_bytes": 1048576, "overflow": "oldest displayed rows evicted with visible count", "stop": "f, Ctrl-C, navigation, inspection or error; explicit restart captures a new current end"},
        "configuration": {
            "system_discovery": {"required": false, "default": false, "type": "boolean", "purpose": "Enable Servers view via $SYS.REQ.SERVER.PING.STATSZ. Requires explicit system-account permissions to publish that subject and subscribe to private _INBOX replies. Use jetstream=false for a system-only alias."},
            "kind": {"required": true, "values": ["nats"], "purpose": "Select the NATS connector"},
            "jetstream": {"required": false, "default": true, "type": "boolean", "purpose": "Enable JetStream views and account validation; false allows Core-only servers"},
            "subjects": {"required": false, "default": [], "type": "array of 0..32 unique subjects", "values": "1..1024 UTF-8 bytes each, no whitespace/controls or empty tokens; * matches one token, final > matches remaining tokens", "purpose": "Explicit Core subscription choices; never subscribed automatically"},
            "decoders": {"required": false, "default": [], "type": "array of 0..32 unique exact-subject bindings", "fields": {"subject": "exact subject, no wildcards", "format": "avro or protobuf", "framing": "raw (default) or confluent; explicit only", "schema_file": "raw only; exactly one of schema_file, catalog or buf; absolute regular file, max 256 KiB; Avro JSON or Protobuf binary FileDescriptorSet", "catalog": onetui_schema_source::capabilities(), "registry": onetui_schema_source::registry::capabilities(), "buf": onetui_schema_source::buf::capabilities(), "reader_schema_file": "optional Avro reader JSON, same file limits; applies to files, catalogs and registries", "message_name": "required exact full raw Protobuf message name, 1..1024 bytes; forbidden for Avro and Confluent"}, "purpose": "Decode raw data bytes lazily; --check validates every binding; no effect on subscriptions or permissions"},
            "servers": {"required": true, "type": "array of 1..32 strings", "values": "nats://host:port or tls://host:port, max 1024 bytes each; no credentials or extra URL components", "purpose": "Explicit server allowlist; server-advertised addresses are ignored"},
            "tls": {"required": false, "default": true, "type": "boolean", "purpose": "Require verified TLS; false allows only loopback nats:// servers for development"},
            "ca_file": {"required": false, "default": "native trust roots", "type": "absolute PEM file path, max 4096 bytes; regular file max 1 MiB", "purpose": "Replace native trust roots with this CA bundle; requires TLS; read only when connecting"},
            "cert_file": {"required": "with key_file", "type": "absolute PEM path; max 4096 bytes; regular file max 1 MiB", "purpose": "Client certificate chain for mutual TLS; requires TLS"},
            "key_file": {"required": "with cert_file", "type": "absolute PEM path; max 4096 bytes; regular file max 1 MiB", "purpose": "Unencrypted client private key for mutual TLS; requires TLS"},
            "tls_first": {"required": false, "default": false, "type": "boolean", "purpose": "Perform TLS handshake before receiving server INFO; requires TLS and compatible server"},
            "nkey_env": {"required": false, "type": "environment variable name", "purpose": "NKEY user seed; native nonce signing; excludes other authentication modes"},
            "credentials_env": {"required": false, "type": "environment variable name", "purpose": "Complete standard .creds text containing user JWT and NKEY seed, max 65536 bytes; multiline allowed; excludes other authentication modes"},
            "domain": {"required": false, "default": "default $JS.API prefix", "type": "1..255 ASCII letters, digits, underscores or hyphens", "purpose": "Route JetStream requests to $JS.<domain>.API; requires jetstream=true"},
            "token_env": {"required": false, "type": "environment variable name", "purpose": "Token secret reference, resolved on selection; excludes username/password"},
            "username_env": {"required": "with password_env", "type": "environment variable name", "purpose": "Username reference, resolved on selection"},
            "password_env": {"required": "with username_env", "type": "environment variable name", "purpose": "Password reference, resolved on selection"}
        },
        "permissions": "JetStream browsing: publish on read API subjects and subscribe to private _INBOX replies. JetStream publishing additionally needs publish on the chosen application subject. Core: subscribe only to the chosen configured subject. Consumer creation, pull, ACK and delete permissions are not needed.",
        "unsupported": ["consumer administration", "Core publishing", "arbitrary JetStream API prefixes", "encrypted client private keys"]
    })
}
