[package]
name = "onetui-kafka"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
onetui-core = { path = "../core" }
onetui-avro = { path = "../avro" }
onetui-protobuf = { path = "../protobuf" }
anyhow.workspace = true
rdkafka.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
prost = "0.14"
prost-types = "0.14"

[target.'cfg(unix)'.dependencies]
nix.workspace = true
