[package]
name = "onetui-tui"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
onetui-theme = { path = "../theme" }
onetui-core = { path = "../core" }
anyhow.workspace = true
crossterm.workspace = true
futures-util.workspace = true
ratatui.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tempfile.workspace = true
unicode-segmentation = "1"
unicode-width = "0.2"
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
onetui-postgres = { path = "../postgres" }
tokio-postgres.workspace = true
qdrant-client.workspace = true
nix.workspace = true
