[package]
name = "onetui-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
onetui-core = { path = "../core" }
anyhow.workspace = true
crossterm.workspace = true
futures-util.workspace = true
ratatui.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
onetui-postgres = { path = "../postgres" }
toml.workspace = true
nix.workspace = true
tempfile.workspace = true
