[package]
name = "onetui-core"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
onetui-theme = { path = "../theme" }
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
tokio.workspace = true
tempfile.workspace = true
