FROM archlinux:latest
# --disable-sandbox: pacman's seccomp sandbox fails under qemu amd64 emulation.
RUN pacman --disable-sandbox -Syu --noconfirm
COPY *.pkg.tar.zst /tmp/
RUN pacman --disable-sandbox -U --noconfirm /tmp/onetui-*.pkg.tar.zst
RUN onetui --version
