[package]
name = "onetui-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
onetui-core = { path = "../core" }
anyhow.workspace = true
futures-util.workspace = true
serde.workspace = true
toml.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-postgres-rustls.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
tempfile.workspace = true
